# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit', '0002_auto_20160723_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(related_name='voted_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='thread',
            name='url',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
